=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/15.1R/announce/[FreeBSD 15.1-RELEASE announcement] URL: link:https://www.freebsd.org/releases/15.1R/announce/[] +
link:https://www.freebsd.org/releases/14.5R/schedule/[FreeBSD 14.5-RELEASE schedule] URL: link:https://www.freebsd.org/releases/14.5R/schedule/[] +
link:https://download.freebsd.org/releases/ISO-IMAGES/[FreeBSD releases] URL: link:https://download.freebsd.org/releases/ISO-IMAGES/[] +
link:https://download.freebsd.org/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/snapshots/ISO-IMAGES/[]

Contact: FreeBSD Release Engineering Team <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branches, among other things.

The Team managed 15.1-RELEASE, leading to the official RELEASE build and announcement in June.
Planning has started for the upcoming 14.5-RELEASE, which is due to arrive in September.

The Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/15*, and *stable/14* branches; and also for the *stable/13* branch until its End-of-Life at the end of April.
